use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct Inputs {
    pub sign_messages_padded: Vec<Vec<bool>>,
    pub signatures: Vec<Vec<bool>>,
    pub untrusted_hash: Vec<bool>,
    pub untrusted_height: u64,
    pub untrusted_time_padded: Vec<bool>,
    pub untrusted_time_proof: Vec<Vec<bool>>,
    pub untrusted_timestamp: u64,
    pub untrusted_validators_hash_padded: Vec<bool>,
    pub untrusted_validators_padded: Vec<Vec<bool>>,
    pub untrusted_chain_id_proof: Vec<Vec<bool>>,
    pub untrusted_chain_id_padded: Vec<bool>,
    pub untrusted_version_proof: Vec<Vec<bool>>,
    pub untrusted_version_padded: Vec<bool>,
    pub untrusted_validators_hash_proof: Vec<Vec<bool>>,
    pub untrusted_validator_pub_keys: Vec<Vec<bool>>,
    pub untrusted_validator_vp: Vec<u64>,
    pub trusted_hash: Vec<bool>,
    pub trusted_height: u64,
    pub trusted_time_padded: Vec<bool>,
    pub trusted_time_proof: Vec<Vec<bool>>,
    pub trusted_timestamp: u64,
    pub trusted_next_validators_hash_proof: Vec<Vec<bool>>,
    pub trusted_next_validators_hash_padded: Vec<bool>,
    pub trusted_next_validators_padded: Vec<Vec<bool>>,
    pub trusted_next_validator_pub_keys: Vec<Vec<bool>>,
    pub trusted_next_validator_vp: Vec<u64>,
    pub signature_indices: Vec<u8>,
    pub untrusted_intersect_indices: Vec<u8>,
    pub trusted_next_intersect_indices: Vec<u8>,
}