[package]
name = "tendermint-lc-plonky2"
version = "0.1.0"
edition = "2021"

[dependencies]
plonky2 = "0.1.4"
num = "0.4.1"
serde_json = "1.0.74"
serde = { version = "1.0", features = ["derive"] }
plonky2_crypto = { git = "https://github.com/Electron-Labs/plonky2-crypto" }
rustc-serialize = "0.3.25"
